### ISSUE TITLE
[449] Error: Line number

### ISSUE THREAD

**Issue by maik** [mauroxavierneto/gauntlet_cmm2#1]
I have downloaded the ZIP file and copied its content to a folder named Gauntlet on an SD card. I have used the CMM2 file manager to navigate to the folder and started GAUNTLET.BAS. I get the following error message:

[449] Error: Line number

I am using MMBasic Version 5.05.04b1p.

**Comment by mauroxavierneto** [comment]
Please, update to the last beta firmware, this could fix the problem:
https://geoffg.net/Downloads/Maximite/CMM2_Beta.zip

Tell me if doesn't work.

Em sex., 28 de ago. de 2020 às 13:37, Maik Schmidt <notifications@github.com>
escreveu:

**Comment by maik** [comment]
I have updated the firmware to 5.05.04 and it works great now. Thank you very much!
